-- MySQL Script generated by MySQL Workbench
-- Sat Sep 27 12:55:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ts-backend-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ts-backend-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ts-backend-db` ;
USE `ts-backend-db` ;

-- -----------------------------------------------------
-- Table `ts-backend-db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts-backend-db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts-backend-db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts-backend-db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts-backend-db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts-backend-db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT(2048) NULL,
  `image_link` VARCHAR(1024) NULL,
  `is_available` TINYINT NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_products_1_idx` (`category_id` ASC),
  CONSTRAINT `fk_products_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ts-backend-db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts-backend-db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts-backend-db`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `note` VARCHAR(1024) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_orders_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_orders_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ts-backend-db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts-backend-db`.`order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts-backend-db`.`order_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_products_1_idx` (`order_id` ASC),
  INDEX `fk_order_products_2_idx` (`product_id` ASC),
  CONSTRAINT `fk_order_products_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ts-backend-db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_products_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `ts-backend-db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts-backend-db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts-backend-db`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_carts_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_carts_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ts-backend-db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts-backend-db`.`carts_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ts-backend-db`.`carts_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carts_products_1_idx` (`cart_id` ASC),
  INDEX `fk_carts_products_2_idx` (`product_id` ASC),
  CONSTRAINT `fk_carts_products_1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `ts-backend-db`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_products_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `ts-backend-db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
